import 'dart:ui';
class AppConstant {
static const List<Map<String, dynamic>> dataConversations = [
    {
      'id': 'conv_001',
      'name': 'Đình Nhân',
      'avatar': null,
      'avatarColor': const Color(0xFF4CAF50),
      'lastMessageKey': 'youPrefix',
      'lastMessageContent': 'Nice to meet you',
      'lastMessageTimeValue': 5,
      'lastMessageTimeUnit': 'minutes',
      'unreadCount': 0,
      'isPinned': false,
      'isGroup': false,
    },
    {
      'id': 'conv_002',
      'name': 'Nhóm Dự Án',
      'avatar': null,
      'avatarColor': const Color(0xFF9C27B0),
      'lastMessageKey': 'youPrefix',
      'lastMessageContent': 'Nice to meet you',
      'lastMessageTimeValue': 10,
      'lastMessageTimeUnit': 'minutes',
      'unreadCount': 3,
      'isPinned': false,
      'isGroup': true,
      'memberCount': 5,
    },
    {
      'id': 'conv_003',
      'name': 'Minh Anh',
      'avatar': null,
      'avatarColor': const Color(0xFF2196F3),
      'lastMessageKey': '',
      'lastMessageContent': 'Chào bạn!',
      'lastMessageTimeValue': 30,
      'lastMessageTimeUnit': 'minutes',
      'unreadCount': 0,
      'isPinned': false,
      'isGroup': false,
    },
    {
      'id': 'conv_004',
      'name': 'Nhóm Lớp K18',
      'avatar': null,
      'avatarColor': const Color(0xFFFF9800),
      'lastMessageKey': '',
      'lastMessageContent': 'Ai có tài liệu không?',
      'lastMessageTimeValue': 1,
      'lastMessageTimeUnit': 'hours',
      'unreadCount': 12,
      'isPinned': false,
      'isGroup': true,
      'memberCount': 45,
    },
    {
      'id': 'conv_005',
      'name': 'Tuấn Kiệt',
      'avatar': null,
      'avatarColor': const Color(0xFFE91E63),
      'lastMessageKey': 'youPrefix',
      'lastMessageContent': 'Ok bạn',
      'lastMessageTimeValue': 2,
      'lastMessageTimeUnit': 'hours',
      'unreadCount': 0,
      'isPinned': false,
      'isGroup': false,
    },
  ];
}