// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLKXfjxoC-4E725H5b19Folum3OHJ4UP8',
    appId: '1:1040826455699:android:d538db1624fde8b4675f66',
    messagingSenderId: '1040826455699',
    projectId: 'zalo-lite-47899',
    storageBucket: 'zalo-lite-47899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_a8AxTDvB13GAmu8gXvNMr6eqXDnl2n8',
    appId: '1:1040826455699:ios:a2fffd080e40e3c7675f66',
    messagingSenderId: '1040826455699',
    projectId: 'zalo-lite-47899',
    storageBucket: 'zalo-lite-47899.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCifnV49y6chIf-5Tfsyrh_jC6nurNe3UU',
    appId: '1:1040826455699:web:85f34a5d6dd3fec8675f66',
    messagingSenderId: '1040826455699',
    projectId: 'zalo-lite-47899',
    authDomain: 'zalo-lite-47899.firebaseapp.com',
    storageBucket: 'zalo-lite-47899.firebasestorage.app',
  );

}